apiVersion: v1
kind: Service
metadata:
  name: house-price-predictor-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: house-price-predictor